name: Build and Push Frontend Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.HARBOR_URL }} \
          --username "${{ secrets.HARBOR_USERNAME }}" \
          --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
          -t ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/frontend:latest \
          -t ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/frontend:${{ github.sha }} \
          ./apps/frontend

      - name: Push Latest Image
        run: |
          docker push ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/frontend:latest

      - name: Push SHA Image
        run: |
          docker push ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/frontend:${{ github.sha }}
